"""empty message

Revision ID: 676695bb3de3
Revises: 526dfc134fa5
Create Date: 2024-11-16 13:18:10.461629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676695bb3de3'
down_revision = '526dfc134fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
